---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: crid-spec
  title: RaBe CRID
  description: |
    The RaBe Content Reference Idenitifier Spcification (CRID) defines how we use
    the `crid:` URL scheme as defined by ETSI TS 102 822-4 for CRIDs that use a DNS
    portion delegated to RaBe.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: spec
  lifecycle: experimental
  owner: it-reaktion
